freelunch.uk/Controllers/SpecialistController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using freelunch.uk.Models;
using System.Data.Entity;
using freelunch.uk.Common;

namespace freelunch.uk.Controllers
{
    [RedirectOnError]
    [RequireHttps]
    [Authorize]
    public class SpecialistController : Controller
    {
        public enum SpecialistMessageId
        {
            LinkExists,
            UpdateSuccess,
            DeleteSuccess,
            AddSucess,
            Error
        }

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationDbContext context = new ApplicationDbContext();

        // GET: Specialist
        public ActionResult Index(SpecialistMessageId? message, int tab = 0)
        {
            ViewBag.StatusMessage =
                message == SpecialistMessageId.Error ? "An error has occurred."
                : message == SpecialistMessageId.DeleteSuccess ? "The record has been deleted."
                : message == SpecialistMessageId.AddSucess ? "The record has been created."
                : message == SpecialistMessageId.UpdateSuccess ? "The record have been updated."
                : message == SpecialistMessageId.LinkExists ? "You already have a link to that resource."
                : "";

            ViewBag.Tab = tab;
            var userId = User.Identity.GetUserId();
            var specialist = context.Specialists.FirstOrDefault(x => x.UserId == userId);
            var model = new SpecialistViewModel();

            if (specialist != null)
            {
                model.UserId = specialist.UserId;
                model.Name = specialist.Name;
                model.Description = specialist.Description;
                model.Links = specialist.Links;
                model.Specialisms = specialist.Specialisms;
                model.Locations = specialist.Locations;

                foreach (var location in specialist.Locations)
                {
                    if (string.IsNullOrEmpty(model.DisplayLocation.Name))
                        model.DisplayLocation.Name = location.Name;
                    else
                        model.DisplayLocation.Name += ", " + location.Name;
                }

                //create an array of distinct location names for type ahead
                ViewBag.Locations = context.Locations.Select(x => x.Name).ToList<string>().Distinct(StringComparer.InvariantCultureIgnoreCase).ToArray();
            }

            return View(model);
        }

        // GET: Specialist/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Specialist/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Specialist/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(SpecialistViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Index", model);
                }

                var userId = User.Identity.GetUserId();
                var user = await UserManager.FindByIdAsync(userId);

                if (user == null)
                {
                    return View("Error");
                }

                Specialist specialist = new Specialist();
                specialist.UserId = userId;
                specialist.Name = model.Name;
                specialist.Description = model.Description;

                context.Specialists.Add(specialist);
                context.SaveChanges();

                return RedirectToAction("Index", new { Message = SpecialistMessageId.AddSucess });
            }
            catch
            {
                return View();
            }
        }


        // POST: Specialist/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(SpecialistViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Index", model);
                }

                var userId = User.Identity.GetUserId();
                var user = await UserManager.FindByIdAsync(userId);

                if (user == null)
                {
                    return View("Error");
                }


                var specialist = context.Specialists.FirstOrDefault(x => x.UserId == userId);

                if (specialist == null)
                {
                    return View("Error");
                }

                if (!string.IsNullOrEmpty(model.DisplayLocation.Name))
                {
                    string[] locations = model.DisplayLocation.Name.Split(',');

                    var removeThese = specialist.Locations.Where(l => !locations.Contains(l.Name)).ToList<Location>();

                    foreach (var removeThis in removeThese)
                    {
                        specialist.Locations.Remove(removeThis);
                        context.Locations.Remove(removeThis);
                    }

                    foreach (string location in locations)
                    {
                        if (!specialist.Locations.Any(l => l.Name == location))
                        {
                            Location newloc = new Location();
                            newloc.Name = location;
                            specialist.Locations.Add(newloc);
                        }
                    }
                }

                specialist.Name = model.Name;
                specialist.Description = model.Description;

                context.SaveChanges();

                return RedirectToAction("Index", new { Message = SpecialistMessageId.UpdateSuccess });
            }
            catch
            {
                return View();
            }
        }

        // POST: Specialist/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete()
        {
            try
            {
                var userId = User.Identity.GetUserId();
                var user = await UserManager.FindByIdAsync(userId);

                if (user == null)
                {
                    return View("Error");
                }

                var specialist = context.Specialists.FirstOrDefault(x => x.UserId == userId);

                if (specialist == null)
                {
                    return View("Error");
                }

                int count = specialist.Links.Count - 1;
                for (int i = count; i >= 0; i--)
                {
                    Link link = specialist.Links.ElementAt(i);
                    specialist.Links.Remove(link);
                    context.Links.Remove(link);
                }

                count = specialist.Specialisms.Count - 1;
                for (int i = count; i >= 0; i--)
                {
                    Specialism specialism = specialist.Specialisms.ElementAt(i);
                    specialist.Specialisms.Remove(specialism);
                    context.Specialisms.Remove(specialism);
                }

                count = specialist.Locations.Count - 1;
                for (int i = count; i >= 0; i--)
                {
                    Location location = specialist.Locations.ElementAt(i);
                    specialist.Locations.Remove(location);
                    context.Locations.Remove(location);
                }

                context.Specialists.Attach(specialist);
                context.Specialists.Remove(specialist);

                string result = ValidationHelper.GetValidationResults(specialist);

                if (!string.IsNullOrEmpty(result)) return View("Error"); 

                context.SaveChanges();

                return RedirectToAction("Index", new { Message = SpecialistMessageId.DeleteSuccess });
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditLink(string id, FormCollection collection )
        {
            try
            {
                var link = context.Links.FirstOrDefault(x => x.Id == id);

                if (link == null) return View("Error");

                link.Text = collection["Text"];
                link.URL = collection["URL"];
                link.LinkType = (LinkType)Enum.Parse(typeof(LinkType), collection["LinkType"]);

                if (NotDuplicateLinlk(link))
                {
                    return RedirectToAction("Index", new { Message = SpecialistMessageId.LinkExists, Tab = 1 });
                }

                context.SaveChanges();

                return RedirectToAction("Index", new { Message = SpecialistMessageId.UpdateSuccess, Tab = 1 });
            }
            catch
            {
                return View();
            }
        }

        private bool NotDuplicateLinlk(Link link)
        {
            bool duplicate = false;
            var links = context.Links.Where(l => l.Id != link.Id).ToList();

            foreach (var specl in links)
            {
                if (specl.Specialist.UserId.Equals(link.Specialist.UserId))
                {
                    duplicate = specl.LinkType.Equals(link.LinkType) &&
                                   specl.Text.Equals(link.Text, StringComparison.InvariantCultureIgnoreCase) &&

freelunch.uk/Views/Shared/_Layout.cshtml
@{ 
    
    ViewBag.twitter = "@meetfreelunch";

    string _username = @User.Identity.GetUserName();
    string _userid = @User.Identity.GetUserId();
}

@using Microsoft.AspNet.Identity
@using freelunch.uk.Common


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - freelunch.uk</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/freelunch")
    @Scripts.Render("~/bundles/bootstrap")

    <style type="text/css">
      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

      #wrap > .container {
        padding-top: 60px;
      }
      .container .credit {
        margin: 20px 0;
      }

      code {
        font-size: 80%;
      }

    </style>
</head>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-57924c08fce7c572"></script>

<body>
    <script type="text/javascript">
        var first = "info";
        var last = "meetfreelunch.uk";

    $(function () {
        if (document.cookie.indexOf("cookies") < 0) {
            $('#cookie-consent').slideDown('slow');
        }
        else {
            $('#cookie-consent');
        }

        $('#consent').on('click', function () {
            document.cookie = "cookies=yes; path=/; max-age=" + (5 * 365 * 24 * 60 * 60);
            $('#cookie-consent').slideUp('slow');
        });
        $('#learn-more').on('click', function () {
            location.href = '@Url.Action("Privacy", "Home")';
        })
    });
</script>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div id="cookie-consent" class="cookie-consent">
                This site uses cookies to personalise content and adverts, to provide social media features and to analyse traffic.
                <button class="btn btn-xs btn-white" id="consent">I'm happy with this</button> <button class="btn btn-xs btn-white" id="learn-more">Learn more</button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("meetfreelunch.uk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Specialists", "Home")">
                            <i class="fa fa-users" aria-hidden="true"></i> Specialists
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Lunch", "Home")">
                            <i class="fa fa-cutlery" aria-hidden="true"></i> Lunch
                        </a>
                    </li>
                </ul>

                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="" data-toggle="modal" data-target="#accountMenu">
                                <i class="fa fa-cog" aria-hidden="true"></i> Account
                            </a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="@Url.Action("Register", "Account")">
                                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>  Register
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Login", "Account")">
                                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>  Sign in
                            </a>        
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>

    <div id="accountMenu" class="modal fade" role="dialog" tabindex='-1'>
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close close-button" data-dismiss="modal">
                        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                    </button>
                    <h4 class="modal-title">Account</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>
                                @_username
                            </h4>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            @Html.ActionLink("Manage your account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", @style = "text-decoration: none" })
                        </div>
                        <div class="col-md-6">
                            @Html.Partial("_SpecialistLink")
                            <br />
                            @Html.Partial("_LunchLink")
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Sign out
                        </button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span> Cancel
                        </button>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-4">
                    &copy; @DateTime.Now.Year - meetfreelunch.uk
                </div>
                <div class="col-md-6">
                    Contact us at: <i class="fa fa-envelope" aria-hidden="true"></i>
                    <script type="text/javascript">
                        //document.write('<a href="mailto:' + first + '@@' + last + '" style="text-decoration: none" title="Send us an email">' + first + '@@' + last + '<\/a>');
                        document.write(first + '@@' + last);
                    </script>
                    | <i class="fa fa-twitter" aria-hidden="true"></i>
                    <a href="https://twitter.com/meetfreelunch" style="text-decoration: none" title="Connect with us on twitter" target="_blank"> @ViewBag.twitter</a>
                </div>
                <div class="col-md-2">
                    @Html.ActionLink("Terms and conditions", "Terms", "Home", null, new { @target="_blank", title="Open our terms and conditions in a seperate window" })
                </div>
            </div>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

freelunch.uk/Views/Shared/_LunchLink.cshtml
@{
    string _userid = @User.Identity.GetUserId();
}

@using Microsoft.AspNet.Identity
@using freelunch.uk.Common

@if (Functions.HasLunch(_userid))
{
    @Html.ActionLink("Lunch details", "Index", "Lunch", null, htmlAttributes: new { @style = "text-decoration: none" })
}
else
{
    @Html.ActionLink("Propose a lunch", "Create", "Lunch", null, htmlAttributes: new { @style = "text-decoration: none" })
}

freelunch.uk/Views/Shared/_SpecialistLink.cshtml
@{
    string _userid = @User.Identity.GetUserId();
}

@using Microsoft.AspNet.Identity
@using freelunch.uk.Common

@if (Functions.IsSpecialist(_userid))
{
    @Html.ActionLink("We know you're special", "Index", "Specialist", null, htmlAttributes: new { @style = "text-decoration: none" })
}
else
{
    @Html.ActionLink("Become a specialist", "Create", "Specialist", null, htmlAttributes: new { @style = "text-decoration: none" })
}